apiVersion: apps/v1
kind: Deployment
metadata:
  name: leodemo
  namespace: student-aichinger-niklas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leodemo
  template:
    metadata:
      labels:
        app: leodemo
    spec:
      containers:
        - name: leodemo 
          image: ghcr.io/naichinger/hello-world-leodemo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: leodemo-svc
  namespace: student-aichinger-niklas
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: leodemo 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leodemo-ingress
  namespace: student-aichinger-niklas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /aichinger.niklas/leodemo(.*)$
            pathType: Prefix
            backend:
              service:
                name: leodemo-svc
                port:
                  number: 80
